# Cloud Build configuration for ledger service
#
# Usage:
#   gcloud builds submit --project=spotcanvas-staging --substitutions=_ENV=staging
#   gcloud builds submit --project=spotcanvas-staging --substitutions=_ENV=production

substitutions:
  _REGION: europe-west3
  _ENV: staging
  _SERVICE_PREFIX: spot-canvas-ledger
  _ARTIFACT_REGISTRY: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/spot-canvas
  _IMAGE_NAME: ledger
  _MEMORY: "256Mi"
  _CPU: "1"
  _MIN_INSTANCES: "0"
  _MAX_INSTANCES: "3"
  _CONCURRENCY: "80"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

steps:
  # Step 1: Build the Docker image
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - build
      - -t
      - ${_ARTIFACT_REGISTRY}/${_IMAGE_NAME}:${SHORT_SHA}
      - -t
      - ${_ARTIFACT_REGISTRY}/${_IMAGE_NAME}:latest
      - .

  # Step 2: Push the image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    id: push
    args:
      - push
      - --all-tags
      - ${_ARTIFACT_REGISTRY}/${_IMAGE_NAME}
    waitFor:
      - build

  # Step 3: Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail

        ENV="${_ENV}"
        echo "Deploying ledger to $ENV environment..."

        if [[ "$ENV" == "staging" ]]; then
          SERVICE_NAME="${_SERVICE_PREFIX}-staging"
          SECRET_PREFIX="spot-canvas-staging"
        else
          SERVICE_NAME="${_SERVICE_PREFIX}"
          SECRET_PREFIX="spot-canvas"
        fi

        CLOUDSQL_INSTANCE="${PROJECT_ID}:${_REGION}:spot-canvas-db"

        gcloud run deploy "$SERVICE_NAME" \
          --project="${PROJECT_ID}" \
          --region="${_REGION}" \
          --image="${_ARTIFACT_REGISTRY}/${_IMAGE_NAME}:${SHORT_SHA}" \
          --platform=managed \
          --memory="${_MEMORY}" \
          --cpu="${_CPU}" \
          --min-instances="${_MIN_INSTANCES}" \
          --max-instances="${_MAX_INSTANCES}" \
          --concurrency="${_CONCURRENCY}" \
          --timeout=300s \
          --port=8080 \
          --allow-unauthenticated \
          --add-cloudsql-instances="$CLOUDSQL_INSTANCE" \
          --set-env-vars="ENVIRONMENT=$ENV,LOG_LEVEL=info,CLOUDSQL_INSTANCE=$CLOUDSQL_INSTANCE,DB_NAME=spot_canvas,DB_USER=spot" \
          --set-secrets="DB_PASSWORD=${SECRET_PREFIX}-db-password:latest,NATS_URLS=${SECRET_PREFIX}-nats-url:latest,NATS_CREDS=${SECRET_PREFIX}-nats-creds:latest"

        URL=$(gcloud run services describe "$SERVICE_NAME" \
          --project="${PROJECT_ID}" \
          --region="${_REGION}" \
          --format="value(status.url)" 2>/dev/null || echo "unavailable")
        echo "Deployed to: $URL"
    waitFor:
      - push

images:
  - ${_ARTIFACT_REGISTRY}/${_IMAGE_NAME}:${SHORT_SHA}
  - ${_ARTIFACT_REGISTRY}/${_IMAGE_NAME}:latest

timeout: 600s
