# Cloud Build configuration for ledger service
# Builds Docker image and deploys to Cloud Run (europe-west3)

substitutions:
  _REGION: europe-west3
  _ENV: production
  _SERVICE_NAME: spot-canvas-ledger
  _ARTIFACT_REGISTRY: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/spot-canvas
  _IMAGE_NAME: ledger
  _MEMORY: "256Mi"
  _CPU: "1"
  _MIN_INSTANCES: "1"
  _MAX_INSTANCES: "3"
  _CONCURRENCY: "80"
  _CLOUDSQL_INSTANCE: ""

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

steps:
  # Step 1: Build the Docker image
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - build
      - -t
      - ${_ARTIFACT_REGISTRY}/${_IMAGE_NAME}:${SHORT_SHA}
      - -t
      - ${_ARTIFACT_REGISTRY}/${_IMAGE_NAME}:latest
      - .

  # Step 2: Push the image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    id: push
    args:
      - push
      - --all-tags
      - ${_ARTIFACT_REGISTRY}/${_IMAGE_NAME}
    waitFor:
      - build

  # Step 3: Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail

        ENV="${_ENV}"
        echo "Deploying ledger to $ENV environment..."

        if [[ "$ENV" == "staging" ]]; then
          SERVICE_NAME="${_SERVICE_NAME}-staging"
          SECRET_PREFIX="spot-canvas-staging"
          DB_NAME="spot_canvas_staging"
        else
          SERVICE_NAME="${_SERVICE_NAME}"
          SECRET_PREFIX="spot-canvas"
          DB_NAME="spot_canvas"
        fi

        DEPLOY_CMD=(
          gcloud run deploy "$SERVICE_NAME"
          --project="${PROJECT_ID}"
          --region="${_REGION}"
          --image="${_ARTIFACT_REGISTRY}/${_IMAGE_NAME}:${SHORT_SHA}"
          --platform=managed
          --memory="${_MEMORY}"
          --cpu="${_CPU}"
          --min-instances="${_MIN_INSTANCES}"
          --max-instances="${_MAX_INSTANCES}"
          --concurrency="${_CONCURRENCY}"
          --timeout=300s
          --port=8080
          --allow-unauthenticated
          --set-env-vars="ENVIRONMENT=$ENV,LOG_LEVEL=info"
          --set-secrets="NATS_CREDS=${SECRET_PREFIX}-nats-creds:latest"
          --set-secrets="NATS_URLS=${SECRET_PREFIX}-nats-urls:latest"
        )

        # Add Cloud SQL or DATABASE_URL
        if [[ -n "${_CLOUDSQL_INSTANCE}" ]]; then
          DEPLOY_CMD+=(
            --add-cloudsql-instances="${_CLOUDSQL_INSTANCE}"
            --set-env-vars="CLOUDSQL_INSTANCE=${_CLOUDSQL_INSTANCE},DB_NAME=$DB_NAME,DB_USER=spot"
            --set-secrets="DB_PASSWORD=${SECRET_PREFIX}-db-password:latest"
          )
        else
          DEPLOY_CMD+=(
            --set-secrets="DATABASE_URL=${SECRET_PREFIX}-database-url:latest"
          )
        fi

        "${DEPLOY_CMD[@]}"

        URL=$(gcloud run services describe "$SERVICE_NAME" \
          --project="${PROJECT_ID}" \
          --region="${_REGION}" \
          --format="value(status.url)" 2>/dev/null || echo "unavailable")
        echo "Deployed to: $URL"
    waitFor:
      - push

images:
  - ${_ARTIFACT_REGISTRY}/${_IMAGE_NAME}:${SHORT_SHA}
  - ${_ARTIFACT_REGISTRY}/${_IMAGE_NAME}:latest

timeout: 600s
