# This file was generated by GoReleaser. DO NOT EDIT.
cask "ledger" do
  name "ledger"
  desc "Spot Canvas ledger CLI — query accounts, positions, trades, and import historic data"
  homepage "https://github.com/Spot-Canvas/ledger"
  version "0.1.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ledger"

  on_macos do
    on_intel do
      url "https://github.com/Spot-Canvas/ledger/releases/download/v#{version}/ledger_darwin_amd64.tar.gz"
      sha256 "f75000e8d4c936be6cf1f927a5e26f44f4b5dae951c0169ad0d443a053d3306b"
    end
    on_arm do
      url "https://github.com/Spot-Canvas/ledger/releases/download/v#{version}/ledger_darwin_arm64.tar.gz"
      sha256 "bf7b335a694a46ba9f15dc574f2bf20b12a294ca8ffe7a76045bf295b531e238"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Spot-Canvas/ledger/releases/download/v#{version}/ledger_linux_amd64.tar.gz"
      sha256 "7c49b1ec8cd39b26342a12eb261aa15408d234cfab83800e535436cff3db9017"
    end
  end

  # No zap stanza required
end
