# This file was generated by GoReleaser. DO NOT EDIT.
cask "trader" do
  name "trader"
  desc "Signal Ngn trader CLI — query accounts, positions, trades, and manage live exchange orders"
  homepage "https://github.com/Signal-ngn/trader"
  version "0.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trader"

  on_macos do
    on_intel do
      url "https://github.com/Signal-ngn/trader/releases/download/v#{version}/trader_darwin_amd64.tar.gz"
      sha256 "35cfd245da1ccc8d259bd7ff413ac1a5db7d769b80a6a7cf959e7a1ddd2a57fa"
    end
    on_arm do
      url "https://github.com/Signal-ngn/trader/releases/download/v#{version}/trader_darwin_arm64.tar.gz"
      sha256 "36284fd4591882182c79783361a3bdb7aaf5350a5aec4aef0547c62c47f64c5a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Signal-ngn/trader/releases/download/v#{version}/trader_linux_amd64.tar.gz"
      sha256 "43da712a9ffc9b808a0cc24d0bd4bf1e3a53cd4da907168daee24c351f476ca2"
    end
  end

  # No zap stanza required
end
